version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
  jguweka:
    image: weka
    container_name: weka
    restart: always
    links:
      - "mongodb:mongodb"
    ports:
      - "8080:8080"
      - "8849:8849"
    depends_on:
      - mongodb
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"
