version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
  jguweka:
    image: weka
    restart: always
    links:
      - "mongodb:mongodb"
    ports:
      - "3000"
      - "8849"
    depends_on:
      - mongodb
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - jguweka
  lb:
    image: dockercloud/haproxy
    ports:
        - 80:80
    links:
        - jguweka
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
